// Copyright (c) 2017-2018 The Infinex Core developers
// Distributed under the MIT/X11 software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef USERTRADE_H
#define USERTRADE_H

#include <iostream>
#include <vector>
#include <map>
#include <memory>
#include "tradepair.h"
#include "userconnection.h"

class CUserTrade;
class CUserTradeSetting;
class CUserTradeManager;

typedef std::pair<int, std::shared_ptr<CUserTrade>> PairSignatureUserTrade; //user trade id and trade details
typedef std::map<uint64_t, std::vector<PairSignatureUserTrade>> MapPriceCUserTrade; //price and user trade map
typedef std::map<std::string, std::vector<PairSignatureUserTrade>> MapPubKeyCUserTrade; //user public key and user trade map
typedef std::pair<MapPriceCUserTrade, MapPubKeyCUserTrade> PairPricePubKeyCUserTrade;
typedef std::pair<PairPricePubKeyCUserTrade, PairPricePubKeyCUserTrade> PairBidAskCUserTrade; //bid & ask

extern std::map<int, PairBidAskCUserTrade> mapUserTradeRequest; //trade pair and bid ask data
extern CUserTradeManager userTradeManager;

class CUserTrade
{
private:
	std::vector<unsigned char> userVchSig;
	std::vector<unsigned char> mnVchSig;

public:
	int nTradePairID;
	uint64_t nPrice;
	uint64_t nQuantity;
	uint64_t nAmount;
	int nTradeFee; //this is here to compare with trade pair fee & apply to whichever lower fee (benefit user)	
	std::string nUserPubKey;
	uint64_t nTimeSubmit;
	int nUserTradeID; //generated by MN
	std::string nMNPubKey;
	int64_t nBalanceQty;
	int64_t nBalanceAmount;
	uint64_t nLastUpdate;

	CUserTrade(int nTradePairID, uint64_t nPrice, uint64_t nQuantity, int nTradeFee, std::string nUserPubKey, uint64_t nTimeSubmit) :
		nTradePairID(nTradePairID),
		nPrice(nPrice),
		nQuantity(nQuantity),
		nAmount(nPrice * nQuantity),
		nTradeFee(nTradeFee),
		nUserPubKey(nUserPubKey),
		nTimeSubmit(nTimeSubmit),
		nUserTradeID(0),
		nMNPubKey(""),
		nBalanceQty(nQuantity),
		nBalanceAmount(nAmount),
		nLastUpdate(0)
	{}

	CUserTrade(int nTradePairID, uint64_t nPrice, uint64_t nQuantity, uint64_t nAmount, int nTradeFee, std::string nUserPubKey, uint64_t nTimeSubmit, int nUserTradeID, std::string nMNPubKey, int64_t nBalanceQty, int64_t nBalanceAmount, uint64_t nLastUpdate) :
		nTradePairID(nTradePairID),
		nPrice(nPrice),
		nQuantity(nQuantity),
		nAmount(nAmount),
		nTradeFee(nTradeFee),
		nUserPubKey(nUserPubKey),
		nTimeSubmit(nTimeSubmit),
		nUserTradeID(nUserTradeID),
		nMNPubKey(nMNPubKey),
		nBalanceQty(nBalanceQty),
		nBalanceAmount(nBalanceAmount),
		nLastUpdate(nLastUpdate)
	{}

	CUserTrade() :
		nTradePairID(0),
		nPrice(0),
		nQuantity(0),
		nAmount(0),
		nTradeFee(0),
		nUserPubKey(""),
		nTimeSubmit(0),
		nUserTradeID(0),
		nMNPubKey(""),
		nBalanceQty(0),
		nBalanceAmount(0),
		nLastUpdate(0)
	{}

	bool VerifyUserSignature();
	bool VerifyMNSignature();
	bool MNSign();
	void RelayTo(CNode* node, CConnman& connman);
	void RelayToHandler(CConnman& connman);
};

class CUserTradeManager
{
private:
	std::vector<unsigned char> vchSig;
	uint64_t GetAdjustedTime();

public:
	bool IsSubmittedBidValid(CUserTrade UserTrade, CTradePair TradePair);
	bool IsSubmittedAskValid(CUserTrade UserTrade, CTradePair TradePair);
	bool IsSubmittedBidAmountValid(CUserTrade userTrade, int nTradeFee);
	bool IsSubmittedAskAmountValid(CUserTrade userTrade, int nTradeFee);
	void UserSellRequest(CUserTrade userTrade);
	void UserBuyRequest(CUserTrade userTrade);
	uint64_t GetBidRequiredAmount(uint64_t Price, uint64_t Qty, int TradeFee);
	uint64_t GetAskExpectedAmount(uint64_t Price, uint64_t Qty, int TradeFee);
};

#endif